import React, {Component } from 'react';
import{Grid, Cell} from 'react-mdl';
import Education from './education';
import Experience from './experience';
import Skills from './skills';
import profilePic from '../Images/profilePic.jpg';

class Resume extends Component{
    render(){
        return(
            <div>
                <Grid>
                    <Cell col={5}>
                        <div style={{textAlign:'center'}}>
                            <img src={profilePic}
                            alt="Profile Picture" style={{height:'200px'}}/>
                        </div>
                        <h2>Radha Sudheshna Katta</h2>
                        <h3 style={{color:'grey'}}>Programmer</h3>
                        <hr style={{borderTop:'3px solid #033fb2', width: '50%'}}></hr>
                        <p>Experienced Full Stack Developer with 6.5 years in the industry and high-level
                              proficiency in the following programs: Java, Javascript, jQuery, Hibernate JPA, React JS, Angular, Web Services, Gradle, Jenkins, TIBCO, SQL, expertise with HTML and CSS 
                              seeks to establish a career as the Full Stack Developer. I am very familiar and 
                              experienced with 
                         Web Application Architecture and have worked with a good number of successful development teams.
                         
                            </p>
                        <hr style={{borderTop:'3px solid #033fb2', width: '50%'}}></hr>
                        <h4>Address</h4>
                        <p>301 Traynor Avenue</p>
                        <h4>Phone</h4>
                        <p>+1 548-333-2763</p>
                        <h4>Email</h4>
                        <p>kradha.kradha@gmail.com</p>

                    </Cell>
                    <Cell col={7} className='resume-right-col'>
                        <h2>Education</h2>
                        <Education startYear='2019' endYear="2020" schoolName="Conestoga College"
                        schoolDescription="Post Graduation, Web Design and Development"/>

                        <Education startYear='2008' endYear="2012" schoolName="Velagapudi Ramakrishna 
                        Siddhartha Engineering College"
                        schoolDescription="Bachelor of Technology, Electronics and Communication Engineering"/>

                        <Education startYear='2006' endYear="2008" schoolName="Sri Chaitanya jnior college"
                        schoolDescription="Intermediate, MPC"/>

                        <Education  startYear='2005' endYear="2006" schoolName="G.S.R Model Public school"
                        schoolDescription="High school"/>

                        <hr style={{borderTop:'3px solid #e22947'}}></hr>


                        <h2>Experience</h2>
                        <Experience startYear="2013" endYear="2014"
                        jobName="Capgemini" jobDescription="Senior Software Engineer "
                        projectName="Imaging, Lotus Notes search tool"
                        projectDescription="project is to provide a web platform to the users which will allow them to search 
                        the same documents which they currently feed into the existing Lotus Notes based application.       
                      "
                        Technologies="JSP, Hibernate-JPA, Servlets, TIBCO"></Experience>

                        <Experience startYear="2014" endYear="2016"
                        jobName="Capgemini" jobDescription="Senior Software Engineer "
                        projectName="PDF-Bills , PDF-Policies"
                        projectDescription="project would be to allow the PDF created for the bills generated by TARABS to    
                        be sent for review electronically to the corresponding team of users and then once reviewed, 
                        these bills need to be pushed over to Induction, ARC and sent out for printing as required.  
                      "
                        Technologies="Java, JSF, IceFaces, TIBCO, Oracle SQL"></Experience>

                        <Experience startYear="2016" endYear="2017"
                        jobName="OpenText Technologies" jobDescription="Senior Software Engineer "
                        projectName=" App-Works Platform, Entity - IHub data design file"
                        projectDescription="AppWorks Platform provides the foundation for digital businesses with 
                        intelligently automated, content-rich, connected processes that users can quickly build and    
                        easily modify"
                        Technologies="Backbone JS, JQuery, Java, RestFul Webservices, gradle build"></Experience>
                        
                        <Experience startYear="2017" endYear="2019"
                        jobName="OpenText Technologies" jobDescription="Senior Software Engineer "
                        projectName="UX2.0, Entity support for expression and IHub"
                        projectDescription="Process Experience is the runtime UI where enterprise users can perform various
                        actions for several kinds of business model applications deployed in AppWorks Platform.
                     "
                        Technologies="Aurelia, JavaScript(ES6), HTML, JQuery, Java, RestFul Webservices"></Experience>

                        <hr style={{borderTop:'3px solid #e22947'}}></hr>
                        <h2>Skills</h2>
                        
                        <Skills skill="Java" progress={70} />
                        <Skills skill="javascript" progress={70} />
                        <Skills skill="HTML/CSS" progress={60} />
                        <Skills skill="NodeJS" progress={60} />
                        <Skills skill="Angular" progress={50} />
                        <Skills skill="React JS" progress={50} />
                        <Skills skill="jenkins" progress={50} />
                        <Skills skill="REST" progress={70} />


                    </Cell>
                </Grid>
            </div>
        );
    }

}

export default Resume;